// ALERT
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// AUTH
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOG_OUT = 'LOG_OUT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';

// TOURS
export const FETCH_TOURS = 'FETCH_TOURS';
export const FETCH_TOUR = 'FETCH_TOUR';
export const CREATE_TOUR = 'CREATE_TOUR';
export const UPDATE_TOUR = 'UPDATE_TOUR';
export const DELETE_TOUR = 'DELETE_TOUR';

// REVIEWS
export const FETCH_REVIEWS = 'FETCH_REVIEWS';

// USER
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

// OTHERES
export const STRIPE_CHECKOUT = 'STRIPE_CHECKOUT'
